name: Test with auth

on:
  push:
    branches:
      - 'main'
  pull_request_target:
    branches:
      - 'main'

permissions: {}

jobs:
  test:
    name: Test with auth
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Needed for auth

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            console-api.enforce.dev:443
            dl.enforce.dev:443
            github.com:443
            issuer.enforce.dev:443

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true
      - uses: ./
        with:
          identity: ce2d1984a010471142503340d670612d63ffb9f6/d05d31ba65ec54d1
      - run: chainctl auth status
