name: Test with auth

on:
  push:
    branches:
      - 'main'
  pull_request_target:
    branches:
      - 'main'

permissions: {}

jobs:
  test:
    name: Test with auth
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Needed for auth

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
        with:
          identity: ce2d1984a010471142503340d670612d63ffb9f6/d05d31ba65ec54d1
      - run: chainctl auth status
